name: Build and release
on: push
jobs:
  release-project:
    name: Release build to github Releases
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download content
        uses: actions/download-artifact@v2
        with:
          name: Build-GO
      - name: Archive content
        uses: thedoctor0/zip-release@master
        with:
          filename: site.zip
      - name: Create Github Release
        id: create-new-release
        uses: actions/create-release@v1
        env: 
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v${{ github.run_number }}
          release_name: Release V${{ github.run_number }}

      - name: Upload asset to github release
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create-new-release.outputs.upload_url }}
          asset_path: ./site.zip
          asset_name: site-v${{ github.run_number }}.zip
          asset_content_type: application/zip


  build-project:
    name: Build go project
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: build
        run: go build -o main
      - name: upload build
        uses: actions/upload-artifact@v2
        with:
          name: Build-GO
          path: out/